name: finansmart
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter

  # Iconos
  cupertino_icons: ^1.0.8

  # Cliente HTTP centralizado - Semana 13
  dio: ^5.9.0

  # Serialización de modelos - Semana 13
  json_annotation: ^4.12.0

  # Se mantiene porque algunos servicios de Semana 12 todavía usan http
  http: ^1.6.0

  # Base de datos local - Semana 12
  drift: ^2.34.4
  sqlite3_flutter_libs: ^0.6.0+eol
  path_provider: ^2.1.6
  path: ^1.9.1

  # Identificador único para operaciones offline
  uuid: ^4.6.0

  # Control de conectividad
  connectivity_plus: ^7.3.1

  # Almacenamiento cifrado de credenciales
  flutter_secure_storage: 9.2.4
  image_picker: ^1.2.3
  flutter_local_notifications: ^22.3.1
  permission_handler: ^13.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Reglas de análisis
  flutter_lints: ^6.0.0

  # Generación de código de Drift
  drift_dev: ^2.34.6

  # Generador de código
  build_runner: ^2.16.1

  # Serialización automática JSON - Semana 13
  json_serializable: ^6.11.0

flutter:
  uses-material-design: true